package:
  name: example-cpp-math
  version: "0.1"

source:
  path: ..

build:
  number: 1

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - cmake
    - python
    - pybind11
  host:
    - python
  run:
    - python

test:
  imports:
    - example_cpp_math
  commands:
    - python -c "import example_cpp_math; assert example_cpp_math.add(6, 9) == 15"
